name: Typechecking
on: [ workflow_call ]

concurrency:
  group: typechecking-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  typescript:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup window SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 22621
      - name: Copy platform file to sdk location
        run: powershell -File .\\scripts\\copy-sdk-file.ps1

      - uses: actions/setup-node@v3
        with:
          node-version: 18 # Need for npm >=7.7
          cache: 'npm'

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run typecheck --if-present
